Repository asyncapi/modelina, pull requests merged in 2021-07, with the labels that each got.

#283 feat: enable go generator
  Dockerfile
  docs/generators.md
  docs/presets.md
  sonar-project.properties
  src/generators/go/GoGenerator.ts
  src/generators/go/GoPreset.ts
  src/generators/go/GoRenderer.ts
  src/generators/go/renderers/EnumRenderer.ts
  src/generators/go/renderers/StructRenderer.ts
  src/generators/index.ts
  test/blackbox/AsyncAPI.spec.ts
  test/blackbox/Dummy.spec.ts
  test/blackbox/utils/Utils.ts
  test/generators/go/GoGenerator.spec.ts
  test/generators/go/GoRenderer.spec.ts
Labels: enhancement

#290 fix: publish esm modules and TS types
  package.json
Labels: bug

#294 docs: remove duplicated state property in the example
  README.md
Labels: documentation

#292 fix: wrong import paths
  src/generators/AbstractGenerator.ts
  src/interpreter/InterpretAdditionalItems.ts
  src/interpreter/InterpretAdditionalProperties.ts
Labels: bug
