Repository asyncapi/modelina, pull requests merged in 2022-10, with the labels that each got.

#926 fix: javascript should not split out enums
  src/generators/javascript/JavaScriptGenerator.ts
  test/generators/javascript/JavaScriptGenerator.spec.ts
  test/generators/javascript/__snapshots__/JavaScriptGenerator.spec.ts.snap
Labels: ready-to-merge

#927 fix: typescript marshalling preset not caring about external models
  src/generators/typescript/presets/CommonPreset.ts
  test/generators/typescript/preset/MarshallingPreset.spec.ts
  test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
Labels: ready-to-merge

#928 fix: typescript rendering wrong array type when union
  src/generators/typescript/TypeScriptConstrainer.ts
  test/generators/typescript/TypeScriptConstrainer.spec.ts
  test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
Labels: ready-to-merge

#933 chore: add a new example for JSON schema darft 6
  docs/usage.md
  examples/README.md
  examples/json-schema-draft6-from-object/README.md
  examples/json-schema-draft6-from-object/__snapshots__/index.spec.ts.snap
  examples/json-schema-draft6-from-object/index.spec.ts
  examples/json-schema-draft6-from-object/index.ts
  examples/json-schema-draft6-from-object/package-lock.json
  examples/json-schema-draft6-from-object/package.json
Labels: ready-to-merge

#935 fix: remove unintended characters for typescript marshalling preset
  src/generators/typescript/presets/CommonPreset.ts
  test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
Labels: ready-to-merge

#925 feat: integrate new ParserJS version
  examples/asyncapi-from-parser/index.ts
  examples/integrate-with-react/package.json
  jest.config.js
  package-lock.json
  package.json
  src/models/ProcessorOptions.ts
  src/processors/AsyncAPIInputProcessor.ts
  test/processors/AsyncAPIInputProcessor.spec.ts
  test/processors/InputProcessor.spec.ts
  test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
Labels: enhancement, generator, ready-to-merge

#938 ci: use @swc/jest to speedup tests
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement, dependencies, ready-to-merge

#920 fix: enable processor options to be passed processors
  src/models/ProcessorOptions.ts
  src/processors/AsyncAPIInputProcessor.ts
  src/processors/JsonSchemaInputProcessor.ts
  src/processors/OpenAPIInputProcessor.ts
  src/processors/SwaggerInputProcessor.ts
  src/processors/TypeScriptInputProcessor.ts
Labels: ready-to-merge

#923 feat: adds support for interpreting a combination of allOf and oneOf, and properties and oneOf
  src/interpreter/InterpretAllOf.ts
  src/interpreter/InterpretOneOf.ts
  src/interpreter/InterpretOneOfWithAllOf.ts
  src/interpreter/InterpretOneOfWithProperties.ts
  src/interpreter/InterpretProperties.ts
  src/interpreter/Interpreter.ts
  test/generators/typescript/TypeScriptGenerator.spec.ts
  test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
  test/interpreter/unit/InterpretOneOfWithAllOf.spec.ts
  test/interpreter/unit/Interpreter.spec.ts
  test/interpreter/unit/interpretOneOfWithProperties.spec.ts
Labels: ready-to-merge

#952 fix: pass processor options to JSON schema input processor
  src/processors/JsonSchemaInputProcessor.ts
Labels: ready-to-merge

#944 fix: enum generator for Java should use strict types for it's values
  src/generators/java/JavaConstrainer.ts
  src/generators/java/renderers/EnumRenderer.ts
  test/generators/java/JavaConstrainer.spec.ts
  test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
  test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
Labels: ready-to-merge

#950 docs: add contribution guidelines for processors
  .eslintignore
  README.md
  docs/contributing.md
  jest.config.js
  package.json
  src/generators/AbstractGenerator.ts
  src/generators/java/JavaConstrainer.ts
  src/generators/java/renderers/EnumRenderer.ts
  src/processors/AbstractInputProcessor.ts
  src/processors/AsyncAPIInputProcessor.ts
  src/processors/InputProcessor.ts
  src/processors/JsonSchemaInputProcessor.ts
  src/processors/OpenAPIInputProcessor.ts
  src/processors/SwaggerInputProcessor.ts
  src/processors/TemplateInputProcessor.ts
  src/processors/TypeScriptInputProcessor.ts
  test/processors/InputProcessor.spec.ts
  test/processors/TemplateInputProcessor.spec.ts
  tsconfig.json
Labels: ready-to-merge

#942 feat: update next with master
  .all-contributorsrc
  .github/workflows/automerge-for-humans-merging.yml
  .github/workflows/if-nodejs-release.yml
  .github/workflows/link-check-cron.yml
  .github/workflows/link-check-pr.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/stale-issues-prs.yml
  README.md
  docs/usage.md
  src/generators/dart/presets/JsonSerializablePreset.ts
  src/generators/java/JavaPreset.ts
  src/generators/java/presets/DescriptionPreset.ts
  src/generators/java/presets/JacksonPreset.ts
  src/generators/java/presets/index.ts
  src/generators/java/renderers/EnumRenderer.ts
  src/processors/AsyncAPIInputProcessor.ts
  test/generators/java/JavaGenerator.spec.ts
  test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
  test/generators/java/presets/DescriptionPreset.spec.ts
  test/generators/java/presets/JacksonPreset.spec.ts
  test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
  test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
  test/models/CommonModel.spec.ts
Labels: do-not-merge
